"use client";

import type { components } from "@studio/api-client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, FileUp, Film, ImageIcon, Music2 } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { Badge, Button, Card, Field, PageHeader, SkeletonRows, StatePanel, inputClass } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError, newIdempotencyKey } from "@/lib/problem";

type AssetType=components["schemas"]["MediaAssetType"];
const chunkSize=10*1024*1024;
export default function MediaPage(){return <Suspense fallback={<SkeletonRows/>}><MediaContent/></Suspense>}
function MediaContent(){const q=useSearchParams();const clientId=q.get("clientId")??"";const workspaceId=q.get("workspaceId")??"";const qc=useQueryClient();const[file,setFile]=useState<File|null>(null);const[name,setName]=useState("");const[type,setType]=useState<AssetType>("IMAGE");const[category,setCategory]=useState("HERO_IMAGE");const[rights,setRights]=useState("Owned by client; approved for marketing use");const[progress,setProgress]=useState<string|null>(null);
 const assets=useQuery({queryKey:["media",clientId,workspaceId],enabled:!!clientId&&!!workspaceId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets",{params:{path:{clientId,workspaceId},query:{}}});if(error||!data)throw apiError(error,"Không thể tải media.");return data}});
 const upload=useMutation({mutationFn:async()=>{if(!file)throw new Error("Chọn một tệp.");setProgress("Đang tạo phiên upload bảo mật…");const{data:session,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/media-uploads",{params:{path:{clientId,workspaceId},header:{"Idempotency-Key":newIdempotencyKey()}},body:{assetType:type,category,name:name||file.name,folder:"",filename:file.name,mimeType:file.type,sizeBytes:file.size,usageRights:rights,tags:[category.toLowerCase().replaceAll("_","-")],sourceMetadata:{lastModified:file.lastModified}}});if(error||!session)throw apiError(error,"Không thể tạo phiên upload.");const parts:{partNumber:number;etag:string}[]=[];if(session.multipart){const count=Math.ceil(file.size/chunkSize);for(let index=0;index<count;index++){setProgress(`Đang tải phần ${index+1}/${count}…`);const partNumber=index+1;const{data:req,error:partError}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/media-uploads/{uploadId}/parts/{partNumber}",{params:{path:{clientId,workspaceId,uploadId:session.id,partNumber}}});if(partError||!req)throw apiError(partError,"Không thể ký phần upload.");const response=await put(req,file.slice(index*chunkSize,Math.min(file.size,(index+1)*chunkSize)));if(!response.ok)throw new Error(`R2 từ chối phần ${partNumber}.`);const etag=response.headers.get("etag");if(!etag)throw new Error("R2 không trả ETag; kiểm tra CORS ExposeHeaders.");parts.push({partNumber,etag});}}else{if(!session.request)throw new Error("Phiên upload thiếu URL.");setProgress("Đang tải trực tiếp lên R2…");const response=await put(session.request,file);if(!response.ok)throw new Error("R2 từ chối tệp upload.");}setProgress("Đang xác minh metadata trên server…");const{data,error:completeError}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/media-uploads/{uploadId}/complete",{params:{path:{clientId,workspaceId,uploadId:session.id}},body:{parts}});if(completeError||!data)throw apiError(completeError,"Không thể xác minh tệp.");return data},onSuccess:async()=>{setFile(null);setName("");setProgress(null);await qc.invalidateQueries({queryKey:["media",clientId,workspaceId]})},onError:()=>setProgress(null)});
 const download=async(id:string)=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets/{assetId}/download",{params:{path:{clientId,workspaceId,assetId:id}}});if(error||!data)throw apiError(error,"Không thể tạo link tải.");window.open(data.url,"_blank","noopener,noreferrer")};
 if(!clientId||!workspaceId)return <><PageHeader eyebrow="Tài sản" title="Thư viện media" description="Chọn workspace để upload trực tiếp vào vùng lưu trữ được cô lập."/><StatePanel title="Chưa chọn workspace">Mở workspace từ trang khách hàng, sau đó chọn Media.</StatePanel></>;
 return <><PageHeader eyebrow="R2 trực tiếp" title="Thư viện media" description="Tệp không đi qua máy chủ API. Sau upload, server đối chiếu MIME và dung lượng trước khi asset được xác minh."/>
 <Card className="mb-7 p-6"><h2 className="mb-5 font-serif text-2xl font-bold">Upload asset</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Tệp"><input className={`${inputClass} py-2`} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,audio/mpeg,audio/wav,application/pdf" onChange={e=>{const selected=e.target.files?.[0]??null;setFile(selected);if(selected&&!name)setName(selected.name)}}/></Field><Field label="Tên hiển thị"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Loại"><select className={inputClass} value={type} onChange={e=>setType(e.target.value as AssetType)}><option>IMAGE</option><option>VIDEO</option><option>AUDIO</option><option>LOGO</option><option>BROCHURE</option><option>SCREENSHOT</option><option>SCREEN_RECORDING</option></select></Field><Field label="Danh mục luggage"><select className={inputClass} value={category} onChange={e=>setCategory(e.target.value)}>{["HERO_IMAGE","FRONT_VIEW","SIDE_VIEW","INTERIOR_VIEW","WHEEL_CLOSE_UP","LOCK_CLOSE_UP","HANDLE_CLOSE_UP","PACKSHOT","PULLING_DEMO","OPEN_CLOSE_DEMO","WHEEL_DEMO","LIFESTYLE","AIRPORT","TRAVEL"].map(v=><option key={v}>{v}</option>)}</select></Field><div className="md:col-span-2"><Field label="Quyền sử dụng"><input className={inputClass} value={rights} onChange={e=>setRights(e.target.value)}/></Field></div></div>{progress?<p className="mt-4 text-sm font-semibold text-[var(--moss)]">{progress}</p>:null}{upload.error?<p className="mt-4 text-sm font-semibold text-[var(--coral)]">{upload.error.message}</p>:null}<Button className="mt-5" disabled={!file||upload.isPending} onClick={()=>upload.mutate()}><FileUp className="mr-2 size-4"/>{upload.isPending?"Đang upload…":"Upload & xác minh"}</Button></Card>
 {assets.isLoading?<SkeletonRows/>:assets.error?<StatePanel title="Không thể tải media" tone="danger">{assets.error.message}</StatePanel>:assets.data?.items.length===0?<StatePanel title="Chưa có media">Upload hero image, packshot và các góc sản phẩm bắt buộc.</StatePanel>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.data?.items.map(item=><Card key={item.id} className="p-5"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-[#edf0e7]">{item.assetType==="VIDEO"?<Film className="size-5"/>:item.assetType==="AUDIO"?<Music2 className="size-5"/>:<ImageIcon className="size-5"/>}</span><Badge tone={item.mimeType?"good":"warn"}>{item.mimeType?"Đã xác minh":"Chờ upload"}</Badge></div><h2 className="mt-4 truncate font-serif text-lg font-bold">{item.name}</h2><p className="mt-1 text-xs text-[var(--muted)]">{item.category} · {item.fileSizeBytes?formatBytes(item.fileSizeBytes):"Chưa có tệp"}</p>{item.mimeType?<Button className="mt-4 w-full bg-transparent text-[var(--ink)] ring-1 ring-[var(--line)]" onClick={()=>void download(item.id)}><Download className="mr-2 size-4"/>Tải bản ký</Button>:null}</Card>)}</div>}</>}
function signedHeaders(values:Record<string,string>){const headers=new Headers();for(const[key,value]of Object.entries(values)){const lower=key.toLowerCase();if(lower!=="host"&&lower!=="content-length")headers.set(key,value)}return headers}function put(request:components["schemas"]["PresignedRequest"],body:Blob){return fetch(request.url,{method:request.method,headers:signedHeaders(request.headers),body})}function formatBytes(value:number){if(value<1024*1024)return `${Math.round(value/1024)} KB`;return `${(value/1024/1024).toFixed(1)} MB`}
