"use client";

import type { components } from "@studio/api-client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Save } from "lucide-react";
import Link from "next/link";
import { Suspense, useState } from "react";
import { useScopedEntityId, useStudioScope } from "@/components/studio-scope";
import { Badge, Button, Card, Field, PageHeader, SkeletonRows, StatePanel, inputClass, textareaClass } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError } from "@/lib/problem";
import { studioRoutes } from "@/lib/studio-routes";

type BrandInput=components["schemas"]["BrandProfileInput"];
type Brand=components["schemas"]["BrandProfile"];
export default function BrandPage(){return <Suspense fallback={<SkeletonRows/>}><BrandContent/></Suspense>}
function BrandContent(){const id=useScopedEntityId("brandId");const{clientId,workspaceId}=useStudioScope();
 const brand=useQuery({queryKey:["brand",clientId,workspaceId,id],enabled:!!clientId&&!!workspaceId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/brands/{brandId}",{params:{path:{clientId,workspaceId,brandId:id}}});if(error||!data)throw apiError(error,"Không thể tải thương hiệu.");return data}});
 if(!clientId||!workspaceId)return <StatePanel title="Thiếu phạm vi workspace">Mở hồ sơ từ trang workspace.</StatePanel>;if(brand.isLoading)return <SkeletonRows/>;if(brand.error)return <StatePanel title="Không thể tải thương hiệu" tone="danger">{brand.error.message}</StatePanel>;return <BrandEditor key={brand.data!.version} data={brand.data!} clientId={clientId} workspaceId={workspaceId}/>}
function BrandEditor({data,clientId,workspaceId}:{data:Brand;clientId:string;workspaceId:string}){const[form,setForm]=useState<BrandInput>({...data});const qc=useQueryClient();const save=useMutation({mutationFn:async()=>{const{data:updated,error}=await api.PUT("/clients/{clientId}/workspaces/{workspaceId}/brands/{brandId}",{params:{path:{clientId,workspaceId,brandId:data.id}},body:{...form,version:data.version,changeSummary:"Cập nhật hồ sơ từ Studio"}});if(error||!updated)throw apiError(error,"Không thể lưu hồ sơ.");return updated},onSuccess:async()=>qc.invalidateQueries({queryKey:["brand",clientId,workspaceId,data.id]})});const set=(key:keyof BrandInput,value:unknown)=>setForm(v=>({...v,[key]:value}));return <><Link href={studioRoutes.brands(clientId,workspaceId)} className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--moss)]"><ArrowLeft className="size-4"/>Thương hiệu</Link><PageHeader eyebrow={`Hồ sơ v${data.currentVersion}`} title={data.name} description="Mỗi lần lưu tạo một phiên bản bất biến. Nội dung AI về sau dùng đúng phiên bản được chọn." action={<div className="flex items-center gap-3"><Badge tone="good">{data.status}</Badge><Button disabled={save.isPending} onClick={()=>save.mutate()}><Save className="mr-2 size-4"/>{save.isPending?"Đang lưu…":"Lưu phiên bản"}</Button></div>}/>
 <Card className="p-6"><div className="grid gap-5 md:grid-cols-2"><Field label="Tên thương hiệu"><input className={inputClass} value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Ngôn ngữ chính"><select className={inputClass} value={form.primaryLanguage} onChange={e=>set("primaryLanguage",e.target.value as "vi"|"en")}><option value="vi">Tiếng Việt</option><option value="en">English</option></select></Field><Color label="Màu chính" value={form.primaryColor} onChange={v=>set("primaryColor",v)}/><Color label="Màu phụ" value={form.secondaryColor} onChange={v=>set("secondaryColor",v)}/><div className="md:col-span-2"><Field label="Giọng điệu"><textarea className={textareaClass} value={form.toneOfVoice??""} onChange={e=>set("toneOfVoice",e.target.value)}/></Field></div><div className="md:col-span-2"><Field label="Đối tượng mục tiêu"><textarea className={textareaClass} value={form.targetAudience??""} onChange={e=>set("targetAudience",e.target.value)}/></Field></div><Field label="Thông điệp chính"><input className={inputClass} value={form.mainMessage??""} onChange={e=>set("mainMessage",e.target.value)}/></Field><Field label="CTA mặc định"><input className={inputClass} value={form.defaultCta??""} onChange={e=>set("defaultCta",e.target.value)}/></Field><Field label="Website"><input className={inputClass} type="url" value={form.website??""} onChange={e=>set("website",e.target.value||null)}/></Field><Field label="Điện thoại"><input className={inputClass} value={form.phoneNumber??""} onChange={e=>set("phoneNumber",e.target.value||null)}/></Field><Field label="Thuật ngữ ưu tiên (mỗi dòng)"><textarea className={textareaClass} value={(form.preferredTerminology??[]).join("\n")} onChange={e=>set("preferredTerminology",e.target.value.split("\n").map(v=>v.trim()).filter(Boolean))}/></Field><Field label="Thuật ngữ cấm (mỗi dòng)"><textarea className={textareaClass} value={(form.prohibitedTerminology??[]).join("\n")} onChange={e=>set("prohibitedTerminology",e.target.value.split("\n").map(v=>v.trim()).filter(Boolean))}/></Field><div className="md:col-span-2"><Field label="Tuyên bố miễn trừ"><textarea className={textareaClass} value={form.defaultDisclaimer??""} onChange={e=>set("defaultDisclaimer",e.target.value)}/></Field></div></div>{save.error?<p className="mt-4 text-sm font-semibold text-[var(--coral)]">{save.error.message}</p>:null}</Card></>}
function Color({label,value,onChange}:{label:string;value?:string|null;onChange:(v:string|null)=>void}){return <Field label={label}><div className="flex gap-3"><input aria-label={`${label} picker`} className="size-11 rounded-xl border border-[var(--line)] bg-white p-1" type="color" value={value??"#26664f"} onChange={e=>onChange(e.target.value)}/><input className={inputClass} value={value??""} placeholder="#26664f" onChange={e=>onChange(e.target.value||null)}/></div></Field>}
