"use client";

import type { components } from "@studio/api-client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, ExternalLink, Link2, Plus, Unlink, Upload, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { usePermissions } from "@/components/auth-context";
import { MediaAssetPreview } from "@/components/media-asset-preview";
import { MediaUploader, type MediaScope } from "@/components/media-uploader";
import { Badge, Button, Card, SkeletonRows, StatePanel, inputClass } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError } from "@/lib/problem";
import { studioRoutes } from "@/lib/studio-routes";

type Product = components["schemas"]["Product"];
type Asset = components["schemas"]["MediaAsset"];
type AssetStatus = components["schemas"]["ContentStatus"];
type ProductScope = MediaScope & { productId: string };

const categoryLabels: Record<string, string> = {
  HERO_IMAGE: "Ảnh hero",
  FRONT_VIEW: "Mặt trước",
  SIDE_VIEW: "Mặt bên",
  INTERIOR_VIEW: "Nội thất",
  PACKSHOT: "Packshot",
};
const visualTypes = new Set(["IMAGE", "VIDEO", "LOGO", "SCREENSHOT", "SCREEN_RECORDING"]);

export function ProductMediaPanel({ product, path }: { product: Product; path: ProductScope }) {
  const { canOperate, canReview } = usePermissions();
  const qc = useQueryClient();
  const scope = useMemo(() => ({ clientId: path.clientId, workspaceId: path.workspaceId }), [path.clientId, path.workspaceId]);
  const [showUpload, setShowUpload] = useState(false);
  const [candidateId, setCandidateId] = useState("");
  const assets = useQuery({ queryKey: ["media", path.clientId, path.workspaceId, "product", path.productId], queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets", { params: { path: scope, query: { productId: path.productId } } }); if (error || !data) throw apiError(error, "Không thể tải media sản phẩm."); return data; } });
  const readiness = useQuery({ queryKey: ["product-media-readiness", path.clientId, path.workspaceId, path.productId], queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/media-readiness", { params: { path } }); if (error || !data) throw apiError(error, "Không thể kiểm tra mức sẵn sàng của media."); return data; } });
  const library = useQuery({ queryKey: ["media", path.clientId, path.workspaceId, "attach-candidates"], enabled: canOperate, queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets", { params: { path: scope } }); if (error || !data) throw apiError(error, "Không thể tải Media Library."); return data; } });
  const candidates = useMemo(() => library.data?.items.filter((asset) => !asset.brandId && !asset.productId && asset.status !== "ARCHIVED" && visualTypes.has(asset.assetType)) ?? [], [library.data]);
  const refresh = useCallback(async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["media", path.clientId, path.workspaceId] }), qc.invalidateQueries({ queryKey: ["product-media-readiness", path.clientId, path.workspaceId, path.productId] }), qc.invalidateQueries({ queryKey: ["product", path.clientId, path.workspaceId, path.productId] }), qc.invalidateQueries({ queryKey: ["products", path.clientId, path.workspaceId] })]); }, [path.clientId, path.productId, path.workspaceId, qc]);
  const attach = useMutation({ mutationFn: async () => { const asset = candidates.find((item) => item.id === candidateId); if (!asset) throw new Error("Chọn một asset chưa gắn sản phẩm."); const { data, error } = await api.PUT("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/media-assets/{assetId}", { params: { path: { ...path, assetId: asset.id } }, body: { version: asset.version } }); if (error || !data) throw apiError(error, "Không thể gắn asset; asset có thể đã thuộc sản phẩm khác."); return data; }, onSuccess: async () => { setCandidateId(""); await refresh(); } });
  const approveProduct = useMutation({ mutationFn: async () => { const { data, error } = await api.PATCH("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/status", { params: { path }, body: { status: "APPROVED", version: product.version } }); if (error || !data) throw apiError(error, "Sản phẩm chỉ được duyệt khi đủ media bắt buộc đã duyệt."); return data; }, onSuccess: refresh });

  return <section className="mb-8" aria-labelledby="product-media-title">
    <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h2 id="product-media-title" className="font-serif text-2xl font-bold">Hình ảnh & video sản phẩm</h2><p className="mt-1 max-w-3xl text-sm text-[var(--muted)]">Asset vẫn nằm trong Media Library. Khu vực này chỉ lọc theo sản phẩm và kiểm tra điều kiện dùng cho video.</p></div><div className="flex flex-wrap gap-2"><Link className="inline-flex min-h-11 items-center rounded-full bg-white px-4 text-sm font-bold ring-1 ring-[var(--line)]" href={studioRoutes.media(path.clientId, path.workspaceId)}>Media Library<ExternalLink className="ml-2 size-4" /></Link>{canOperate ? <Button onClick={() => setShowUpload((value) => !value)}>{showUpload ? <X className="mr-2 size-4" /> : <Upload className="mr-2 size-4" />}{showUpload ? "Đóng upload" : "Upload cho sản phẩm"}</Button> : null}</div></div>
    <Card className="mb-5 p-5"><div className="flex flex-wrap items-center gap-3"><div className="flex-1"><h3 className="font-bold">Readiness để duyệt Product Truth</h3><p className="mt-1 text-xs text-[var(--muted)]">Mỗi danh mục bắt buộc cần ít nhất một asset APPROVED, còn hạn và đã xác minh upload.</p></div><Badge tone={readiness.data?.ready ? "good" : "warn"}>{readiness.data?.ready ? "Đủ media" : "Chưa đủ media"}</Badge>{canReview && product.status !== "APPROVED" ? <Button disabled={!readiness.data?.ready || approveProduct.isPending} onClick={() => approveProduct.mutate()}><Check className="mr-2 size-4" />Duyệt sản phẩm</Button> : null}</div>{readiness.isLoading ? <div className="mt-4"><SkeletonRows /></div> : readiness.error ? <p role="alert" className="mt-3 text-sm text-[var(--coral)]">{readiness.error.message}</p> : <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{readiness.data?.requirements.map((requirement) => <div key={requirement.category} className={`rounded-xl border p-3 ${requirement.ready ? "border-[#b7c8ae] bg-[#f2f7ec]" : "border-[#e8c98f] bg-[#fff8e8]"}`}><div className="flex items-center gap-2">{requirement.ready ? <Check className="size-4 text-[var(--moss)]" /> : <Plus className="size-4 text-[#996b16]" />}<span className="text-sm font-bold">{categoryLabels[requirement.category] ?? requirement.category}</span></div><p className="mt-1 text-xs text-[var(--muted)]">{requirement.approvedAssets}/{requirement.totalAssets} đã duyệt</p></div>)}</div>}{approveProduct.error ? <p role="alert" className="mt-3 text-sm text-[var(--coral)]">{approveProduct.error.message}</p> : null}</Card>
    {showUpload ? <div className="mb-5"><MediaUploader key={`${path.productId}:uploader`} scope={scope} productId={path.productId} visualOnly onUploaded={refresh} /></div> : null}
    {canOperate ? <Card className="mb-5 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center"><div className="flex-1"><h3 className="text-sm font-bold">Gắn asset có sẵn</h3><p className="mt-1 text-xs text-[var(--muted)]">Chỉ hiện visual asset chưa thuộc sản phẩm nào; hệ thống không tự chuyển asset giữa hai sản phẩm.</p></div><select aria-label="Asset có sẵn trong Media Library" className={`${inputClass} md:max-w-md`} value={candidateId} onChange={(event) => setCandidateId(event.target.value)}><option value="">Chọn asset chưa gắn sản phẩm</option>{candidates.map((asset) => <option key={asset.id} value={asset.id}>{asset.name} · {asset.category || "chưa phân loại"} · {asset.status}</option>)}</select><Button disabled={!candidateId || attach.isPending} onClick={() => attach.mutate()}><Link2 className="mr-2 size-4" />Gắn asset</Button></div>{attach.error ? <p role="alert" className="mt-3 text-sm text-[var(--coral)]">{attach.error.message}</p> : null}</Card> : null}
    {assets.isLoading ? <SkeletonRows /> : assets.error ? <StatePanel title="Không thể tải Product Media" tone="danger">{assets.error.message}</StatePanel> : assets.data?.items.length === 0 ? <StatePanel title="Sản phẩm chưa có media">Upload trực tiếp tại đây hoặc gắn asset có sẵn từ Media Library. Video pipeline sẽ chỉ nhận asset đã được duyệt.</StatePanel> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{assets.data?.items.map((asset) => <ProductAssetCard key={asset.id} asset={asset} path={path} scope={scope} canOperate={canOperate} canReview={canReview} refresh={refresh} />)}</div>}
  </section>;
}

function ProductAssetCard({ asset, path, scope, canOperate, canReview, refresh }: { asset: Asset; path: ProductScope; scope: MediaScope; canOperate: boolean; canReview: boolean; refresh: () => Promise<unknown> }) {
  const status = useMutation({ mutationFn: async (next: AssetStatus) => { const { data, error } = await api.PATCH("/clients/{clientId}/workspaces/{workspaceId}/media-assets/{assetId}/status", { params: { path: { ...scope, assetId: asset.id } }, body: { status: next, version: asset.version } }); if (error || !data) throw apiError(error, "Asset đã thay đổi; hãy làm mới trước khi duyệt."); return data; }, onSuccess: refresh });
  const detach = useMutation({ mutationFn: async () => { if (!window.confirm(`Gỡ “${asset.name}” khỏi sản phẩm? Asset vẫn được giữ trong Media Library.`)) return false; const { data, error } = await api.DELETE("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/media-assets/{assetId}", { params: { path: { ...path, assetId: asset.id } }, body: { version: asset.version } }); if (error || !data) throw apiError(error, "Không thể gỡ asset đang được fact, claim, scene hoặc edit video sử dụng."); return true; }, onSuccess: (changed) => changed ? refresh() : undefined });
  const open = async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets/{assetId}/download", { params: { path: { ...scope, assetId: asset.id } } }); if (error || !data) throw apiError(error, "Không thể mở asset."); window.open(data.url, "_blank", "noopener,noreferrer"); };
  return <Card className="overflow-hidden"><MediaAssetPreview asset={asset} scope={scope} /><div className="p-4"><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><h3 className="truncate font-bold">{asset.name}</h3><p className="mt-1 text-xs text-[var(--muted)]">{asset.category || "Chưa phân loại"}</p></div><Badge tone={asset.status === "APPROVED" ? "good" : asset.status === "REJECTED" ? "danger" : "warn"}>{asset.status}</Badge></div>{!asset.readyForUse ? <p className="mt-2 text-xs font-semibold text-[#79580b]">Asset đang được kiểm tra checksum.</p> : null}{asset.expiresAt ? <p className="mt-2 text-xs text-[var(--muted)]">Quyền dùng đến {new Date(asset.expiresAt).toLocaleDateString("vi-VN")}</p> : null}{status.error || detach.error ? <p role="alert" className="mt-3 text-xs text-[var(--coral)]">{status.error?.message ?? detach.error?.message}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><Button className="bg-white px-3 text-[var(--ink)] ring-1 ring-[var(--line)]" disabled={!asset.mimeType} onClick={() => void open()}>Mở</Button>{canReview && asset.status !== "APPROVED" ? <Button className="px-3" disabled={status.isPending || !asset.readyForUse} onClick={() => status.mutate("APPROVED")}><Check className="mr-1 size-4" />Duyệt</Button> : null}{canReview && asset.status !== "REJECTED" ? <Button className="bg-[var(--coral)] px-3" disabled={status.isPending} onClick={() => status.mutate("REJECTED")}><X className="mr-1 size-4" />Từ chối</Button> : null}{canOperate ? <Button className="bg-white px-3 text-[var(--coral)] ring-1 ring-[var(--line)]" disabled={detach.isPending} onClick={() => detach.mutate()}><Unlink className="mr-1 size-4" />Gỡ khỏi sản phẩm</Button> : null}</div></div></Card>;
}
