"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { PackageOpen, Plus, Search } from "lucide-react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { usePermissions } from "@/components/auth-context";
import { Badge, Button, Card, Field, PageHeader, SkeletonRows, StatePanel, inputClass } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError, newIdempotencyKey } from "@/lib/problem";

export default function ProductsPage(){return <Suspense fallback={<SkeletonRows/>}><ProductsContent/></Suspense>}
function ProductsContent(){const {canOperate}=usePermissions();const q=useSearchParams();const clientId=q.get("clientId")??"";const workspaceId=q.get("workspaceId")??"";const qc=useQueryClient();const[search,setSearch]=useState("");const[show,setShow]=useState(false);const[form,setForm]=useState({name:"",sku:"",model:"",category:"Vali du lịch",luggageType:"CARRY_ON",sizeInches:"20",dimensions:"55,36,23",weight:"2.9",capacity:"38",material:"Polycarbonate",wheelType:"Spinner 360°",wheelCount:"4",lockType:"TSA",handleType:"Telescopic",warranty:"5 năm",colors:"Đen"});
 const products=useQuery({queryKey:["products",clientId,workspaceId,search],enabled:!!clientId&&!!workspaceId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products",{params:{path:{clientId,workspaceId},query:{search:search||undefined}}});if(error||!data)throw apiError(error,"Không thể tải sản phẩm.");return data}});
 const create=useMutation({mutationFn:async()=>{const[heightCm=0,widthCm=0,depthCm=0]=form.dimensions.split(",").map(Number);const{data,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/products",{params:{path:{clientId,workspaceId},header:{"Idempotency-Key":newIdempotencyKey()}},body:{name:form.name,sku:form.sku,model:form.model,category:form.category,verticalKey:"travel-luggage",shortDescription:"",longDescription:"",intendedAudience:"",changeSummary:"Bản sản phẩm đầu tiên",verticalData:{luggageType:form.luggageType,sizeInches:Number(form.sizeInches),externalDimensions:{heightCm,widthCm,depthCm},emptyWeightKg:Number(form.weight),capacityLiters:Number(form.capacity),shellMaterial:form.material,wheelType:form.wheelType,wheelCount:Number(form.wheelCount),lockType:form.lockType,handleType:form.handleType,interiorCompartments:[],expandable:false,waterResistance:"Không công bố",warranty:form.warranty,availableColors:form.colors.split(",").map(v=>v.trim()).filter(Boolean)},features:[],benefits:[],differentiators:[],variants:[]}});if(error||!data)throw apiError(error,"Không thể tạo sản phẩm.");return data},onSuccess:async()=>{setShow(false);await qc.invalidateQueries({queryKey:["products",clientId,workspaceId]})}});
 if(!clientId||!workspaceId)return <><PageHeader eyebrow="Danh mục" title="Sản phẩm" description="Chọn workspace trước khi quản lý sản phẩm để đảm bảo cô lập dữ liệu."/><StatePanel title="Chưa chọn workspace">Mở một khách hàng, chọn workspace, rồi đi tới Sản phẩm.</StatePanel></>;
 const field=(key:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm(v=>({...v,[key]:e.target.value}));return <><PageHeader eyebrow="Product Truth" title="Sản phẩm" description="Dữ liệu ngành hàng được kiểm tra bằng JSON Schema trước khi lưu; fact đã khóa không thể bị AI thay đổi." action={canOperate ? <Button onClick={()=>setShow(v=>!v)}><Plus className="mr-2 size-4"/>Thêm vali</Button> : undefined}/>
 {canOperate && show?<Card className="mb-6 p-6"><h2 className="mb-5 font-serif text-2xl font-bold">Sản phẩm travel-luggage</h2><div className="grid gap-4 md:grid-cols-3"><Field label="Tên sản phẩm"><input className={inputClass} value={form.name} onChange={field("name")}/></Field><Field label="SKU"><input className={inputClass} value={form.sku} onChange={field("sku")}/></Field><Field label="Model"><input className={inputClass} value={form.model} onChange={field("model")}/></Field><Field label="Loại"><select className={inputClass} value={form.luggageType} onChange={field("luggageType")}><option value="CARRY_ON">Carry-on</option><option value="CHECKED">Checked luggage</option><option value="SET">Luggage set</option></select></Field><Field label="Kích thước (inch)"><input className={inputClass} type="number" value={form.sizeInches} onChange={field("sizeInches")}/></Field><Field label="Dài,rộng,sâu (cm)"><input className={inputClass} value={form.dimensions} onChange={field("dimensions")}/></Field><Field label="Trọng lượng rỗng (kg)"><input className={inputClass} type="number" step="0.1" value={form.weight} onChange={field("weight")}/></Field><Field label="Dung tích (L)"><input className={inputClass} type="number" value={form.capacity} onChange={field("capacity")}/></Field><Field label="Chất liệu vỏ"><input className={inputClass} value={form.material} onChange={field("material")}/></Field><Field label="Loại bánh xe"><input className={inputClass} value={form.wheelType} onChange={field("wheelType")}/></Field><Field label="Số bánh"><input className={inputClass} type="number" value={form.wheelCount} onChange={field("wheelCount")}/></Field><Field label="Loại khóa"><input className={inputClass} value={form.lockType} onChange={field("lockType")}/></Field><Field label="Loại tay kéo"><input className={inputClass} value={form.handleType} onChange={field("handleType")}/></Field><Field label="Bảo hành"><input className={inputClass} value={form.warranty} onChange={field("warranty")}/></Field><Field label="Màu (phân cách dấu phẩy)"><input className={inputClass} value={form.colors} onChange={field("colors")}/></Field></div>{create.error?<p className="mt-4 text-sm font-semibold text-[var(--coral)]">{create.error.message}</p>:null}<div className="mt-5 flex gap-3"><Button disabled={create.isPending||form.name.length<2||!form.sku} onClick={()=>create.mutate()}>{create.isPending?"Đang kiểm tra…":"Tạo bản nháp"}</Button><Button className="bg-transparent text-[var(--ink)] ring-1 ring-[var(--line)]" onClick={()=>setShow(false)}>Hủy</Button></div></Card>:null}
 <div className="mb-5 flex items-center gap-3 rounded-2xl border border-[var(--line)] bg-white px-4"><Search className="size-4 text-[var(--muted)]"/><input aria-label="Tìm sản phẩm" className="min-h-11 w-full bg-transparent text-sm outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tên hoặc SKU"/></div>{products.isLoading?<SkeletonRows/>:products.error?<StatePanel title="Không thể tải sản phẩm" tone="danger">{products.error.message}</StatePanel>:products.data?.items.length===0?<StatePanel title="Chưa có sản phẩm">Thêm sản phẩm travel-luggage đầu tiên và sau đó duyệt Product Truth.</StatePanel>:<div className="grid gap-4 md:grid-cols-2">{products.data?.items.map(item=><Link key={item.id} href={`/products/${item.id}?clientId=${clientId}&workspaceId=${workspaceId}`}><Card className="flex h-full gap-4 p-5 transition hover:border-[var(--moss)]"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#edf0e7]"><PackageOpen className="size-5 text-[var(--moss)]"/></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-serif text-xl font-bold">{item.name}</h2><Badge tone={item.status==="APPROVED"?"good":"warn"}>{item.status}</Badge></div><p className="mt-2 text-sm text-[var(--muted)]">SKU {item.sku} · {item.category}</p></div></Card></Link>)}</div>}</>}
