"use client";

import type { components } from "@studio/api-client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Ban, CirclePlay, RefreshCw, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { Badge, Button, Card, PageHeader, SkeletonRows, StatePanel } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError } from "@/lib/problem";

type Job = components["schemas"]["OperationsJob"];
const number = new Intl.NumberFormat("vi-VN", { maximumFractionDigits: 2 });
const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 4 });

export default function OperationsPage() {
  const overview = useQuery({ queryKey: ["operations-overview"], refetchInterval: 10_000, queryFn: async () => { const { data, error } = await api.GET("/operations/overview"); if (error || !data) throw apiError(error, "Không thể tải Operations Console."); return data; } });
  const qc = useQueryClient();
  const [maintenanceReason, setMaintenanceReason] = useState("Planned maintenance");
  const maintenance = useMutation({ mutationFn: async (enabled: boolean) => { if (!window.confirm(`${enabled ? "Bật" : "Tắt"} maintenance mode?`)) return; const { error } = await api.PUT("/operations/maintenance", { body: { enabled, reason: maintenanceReason } }); if (error) throw apiError(error, "Không thể cập nhật maintenance mode."); }, onSuccess: async () => qc.invalidateQueries({ queryKey: ["operations-overview"] }) });
  const data = overview.data;
  return <><PageHeader eyebrow="Admin only" title="Operations Console" description="Queue depth, failed/stuck jobs, provider failures, costs, storage, versions, audit and safe runtime configuration. Không hiển thị secret." action={<Button className="bg-white text-[var(--ink)] ring-1 ring-[var(--line)]" onClick={() => void overview.refetch()}><RefreshCw className="mr-2 size-4" />Làm mới</Button>} />
    {overview.isLoading ? <SkeletonRows /> : overview.error ? <StatePanel title="Operations Console không khả dụng" tone="danger">{overview.error.message}</StatePanel> : data ? <>
      {data.maintenanceMode ? <div className="mb-6 flex items-center gap-3 rounded-2xl border border-[#efb6aa] bg-[#fff0ea] p-4 text-sm font-semibold"><ShieldAlert className="size-5 text-[var(--coral)]" />Maintenance mode đang chặn toàn bộ mutation ngoài control endpoint.</div> : null}
      <div className="mb-3 flex flex-wrap items-center gap-2 text-xs text-[var(--muted)]"><Badge tone="good">API {data.apiHealth}</Badge><span>Generated {new Date(data.generatedAt).toLocaleString("vi-VN")}</span><span>· Cleanup gần nhất {data.lastMaintenanceAt ? new Date(data.lastMaintenanceAt).toLocaleString("vi-VN") : "chưa chạy"}</span></div>
      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Daily provider cost" value={usd.format(data.dailyCostUsd)} /><Metric label="Monthly provider cost" value={usd.format(data.monthlyCostUsd)} /><Metric label="Attempt factor" value={`${number.format(data.attemptFactor)}×`} /><Metric label="Object storage" value={bytes(data.storageBytes)} /></div>
      <div className="mb-6 grid gap-6 xl:grid-cols-2"><Card className="p-6"><h2 className="font-serif text-xl font-bold">River queues</h2><div className="mt-4 grid gap-2">{data.queues.map((item) => <div key={`${item.queue}-${item.state}`} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-2xl bg-[#f4f5ef] px-4 py-3 text-sm"><span className="font-semibold">{item.queue} <span className="text-[var(--muted)]">· {item.state}</span></span><Badge tone={item.state === "discarded" ? "danger" : item.state === "running" ? "good" : "neutral"}>{item.count}</Badge><span className="text-xs text-[var(--muted)]">oldest {duration(item.oldestAgeSeconds)}</span></div>)}</div></Card><Card className="p-6"><h2 className="font-serif text-xl font-bold">Failures</h2><dl className="mt-4 grid grid-cols-2 gap-3">{Object.entries(data.failures).map(([key, value]) => <div key={key} className="rounded-2xl bg-[#fff4ef] p-4"><dt className="text-xs uppercase text-[var(--muted)]">{key}</dt><dd className="mt-2 font-serif text-2xl font-bold">{value}</dd></div>)}</dl></Card></div>
      <div className="mb-6 grid gap-6 xl:grid-cols-2"><StateBreakdown title="Seedance task state" items={data.seedanceTasks} /><StateBreakdown title="Render worker state" items={data.renderJobs} /></div>
      <Card className="mb-6 overflow-hidden"><div className="p-6"><h2 className="font-serif text-xl font-bold">Running, failed & stuck jobs</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#edf0e7] text-xs uppercase text-[var(--muted)]"><tr>{["ID", "Kind", "Queue", "State", "Attempt", "Age", "Control"].map((label) => <th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody>{data.jobs.map((job) => <JobRow key={job.id} job={job} />)}</tbody></table></div></Card>
      <div className="mb-6 grid gap-6 xl:grid-cols-2"><CostList title="Cost by client" items={data.costByClient} /><CostList title="Cost by campaign" items={data.costByCampaign} /></div>
      {data.costAnomalies.length ? <Card className="mb-6 border-[#efb6aa] bg-[#fff4ef] p-6"><h2 className="font-serif text-xl font-bold">Cost anomalies</h2><div className="mt-4 grid gap-3">{data.costAnomalies.map((item) => <div key={item.id}><Badge tone="warn">{item.severity}</Badge><strong className="ml-2 text-sm">{item.title}</strong><p className="mt-1 text-xs text-[var(--muted)]">{item.message} · {new Date(item.createdAt).toLocaleString("vi-VN")}</p></div>)}</div></Card> : null}
      <div className="mb-6 grid gap-6 xl:grid-cols-2"><Card className="p-6"><h2 className="font-serif text-xl font-bold">Webhook logs</h2><div className="mt-4 grid gap-2">{data.webhooks.length ? data.webhooks.map((item, index) => <div key={`${item.provider}-${item.receivedAt}-${index}`} className="flex flex-wrap items-center gap-2 border-b border-[var(--line)] py-2 text-xs"><Badge tone={item.status === "FAILED" ? "danger" : item.status === "PROCESSED" ? "good" : "warn"}>{item.status}</Badge><strong>{item.provider}</strong><span>{item.eventType}</span><span className="ml-auto text-[var(--muted)]">attempt {item.attemptCount} · {new Date(item.receivedAt).toLocaleString("vi-VN")}</span></div>) : <p className="text-sm text-[var(--muted)]">Chưa có webhook.</p>}</div></Card><Card className="p-6"><h2 className="font-serif text-xl font-bold">Provider errors</h2><div className="mt-4 grid gap-2">{data.providerErrors.length ? data.providerErrors.map((item) => <div key={`${item.system}-${item.entityId}`} className="flex flex-wrap items-center gap-2 border-b border-[var(--line)] py-2 text-xs"><Badge tone="danger">{item.system}</Badge><code>{item.code}</code><span className="max-w-52 truncate text-[var(--muted)]">{item.entityId}</span><time className="ml-auto text-[var(--muted)]">{new Date(item.occurredAt).toLocaleString("vi-VN")}</time></div>) : <p className="text-sm text-[var(--muted)]">Không có provider error đã lưu.</p>}</div></Card></div>
      <div className="mb-6 grid gap-6 xl:grid-cols-2"><Card className="p-6"><h2 className="font-serif text-xl font-bold">Provider/model versions</h2><div className="mt-4 grid gap-2">{data.versions.map((item, index) => <div key={`${item.provider}-${item.model}-${index}`} className="rounded-2xl border border-[var(--line)] p-3 text-sm"><strong>{item.provider}</strong><p className="mt-1 text-xs text-[var(--muted)]">{[item.model, item.promptVersion, item.apiVersion].filter(Boolean).join(" · ") || "No version reported"}</p></div>)}</div></Card><Card className="p-6"><h2 className="font-serif text-xl font-bold">Safe configuration</h2><pre className="mt-4 max-h-80 overflow-auto rounded-2xl bg-[var(--ink)] p-4 text-xs leading-5 text-[#d8f18a]">{JSON.stringify(data.safeConfiguration, null, 2)}</pre></Card></div>
      <Card className="mb-6 p-6"><h2 className="font-serif text-xl font-bold">Feature flags & maintenance</h2><div className="mt-4 flex flex-col gap-3 md:flex-row"><input className="min-h-11 flex-1 rounded-2xl border border-[var(--line)] px-4 text-sm" value={maintenanceReason} onChange={(event) => setMaintenanceReason(event.target.value)} maxLength={500} /><Button className="bg-[var(--coral)]" disabled={maintenance.isPending || !maintenanceReason.trim()} onClick={() => maintenance.mutate(!data.maintenanceMode)}>{data.maintenanceMode ? "Tắt maintenance" : "Bật maintenance"}</Button></div><div className="mt-4 flex flex-wrap gap-2">{data.featureFlags.map((item) => <Badge key={item.key} tone={item.enabled ? "warn" : "neutral"}>{item.key}: {item.enabled ? "ON" : "OFF"}</Badge>)}</div></Card>
      <Card className="p-6"><h2 className="font-serif text-xl font-bold">Recent audit trail</h2><div className="mt-4 grid gap-2">{data.auditLogs.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-2 border-b border-[var(--line)] py-2 text-sm"><Badge tone={item.outcome === "SUCCESS" ? "good" : "danger"}>{item.outcome}</Badge><strong>{item.action}</strong><span className="text-[var(--muted)]">{item.entityType}</span><time className="ml-auto text-xs text-[var(--muted)]">{new Date(item.occurredAt).toLocaleString("vi-VN")}</time></div>)}</div></Card>
    </> : null}
  </>;
}

function JobRow({ job }: { job: Job }) {
  const qc = useQueryClient();
  const mutate = useMutation({ mutationFn: async (action: "retry" | "cancel") => { if (!window.confirm(`${action === "retry" ? "Retry" : "Cancel"} River job ${job.id}?`)) return; const request = action === "retry" ? api.POST("/operations/jobs/{riverJobId}/retry", { params: { path: { riverJobId: job.id } } }) : api.POST("/operations/jobs/{riverJobId}/cancel", { params: { path: { riverJobId: job.id } } }); const { error } = await request; if (error) throw apiError(error, `Không thể ${action} job.`); }, onSuccess: async () => qc.invalidateQueries({ queryKey: ["operations-overview"] }) });
  return <tr className="border-t border-[var(--line)]"><td className="px-5 py-4 font-mono text-xs">{job.id}</td><td className="px-5 py-4 font-semibold">{job.kind}</td><td className="px-5 py-4">{job.queue}</td><td className="px-5 py-4"><Badge tone={job.state === "discarded" ? "danger" : job.state === "running" ? "good" : "warn"}>{job.state}</Badge></td><td className="px-5 py-4">{job.attempt}/{job.maxAttempts}</td><td className="px-5 py-4">{duration(job.ageSeconds)}</td><td className="px-5 py-4"><div className="flex gap-2"><button aria-label={`Retry job ${job.id}`} className="rounded-full p-2 hover:bg-[#edf0e7]" disabled={mutate.isPending} onClick={() => mutate.mutate("retry")}><CirclePlay className="size-4" /></button><button aria-label={`Cancel job ${job.id}`} className="rounded-full p-2 text-[var(--coral)] hover:bg-[#fff0ea]" disabled={mutate.isPending} onClick={() => mutate.mutate("cancel")}><Ban className="size-4" /></button></div></td></tr>;
}

function Metric({ label, value }: { label: string; value: string }) { return <Card className="p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--muted)]">{label}</p><p className="mt-3 font-serif text-3xl font-bold">{value}</p></Card>; }
function StateBreakdown({ title, items }: { title: string; items: components["schemas"]["OperationsStateCount"][] }) { return <Card className="p-6"><h2 className="font-serif text-xl font-bold">{title}</h2><div className="mt-4 flex flex-wrap gap-2">{items.length ? items.map((item) => <Badge key={item.state} tone={item.state === "FAILED" ? "danger" : item.state === "APPROVED" || item.state === "REVIEW_REQUIRED" ? "good" : "neutral"}>{item.state}: {item.count}</Badge>) : <span className="text-sm text-[var(--muted)]">Chưa có job.</span>}</div></Card>; }
function CostList({ title, items }: { title: string; items: components["schemas"]["OperationsCostDimension"][] }) { return <Card className="p-6"><h2 className="font-serif text-xl font-bold">{title}</h2><div className="mt-4 grid gap-2">{items.map((item) => <div key={item.id} className="flex justify-between rounded-2xl bg-[#f4f5ef] px-4 py-3 text-sm"><span className="font-semibold">{item.name}</span><strong>{usd.format(item.usd)}</strong></div>)}</div></Card>; }
function duration(seconds: number) { if (seconds < 60) return `${Math.max(0, Math.round(seconds))}s`; if (seconds < 3600) return `${Math.round(seconds / 60)}m`; return `${number.format(seconds / 3600)}h`; }
function bytes(value: number) { const units = ["B", "KB", "MB", "GB", "TB"]; let amount = value; let index = 0; while (amount >= 1024 && index < units.length - 1) { amount /= 1024; index += 1; } return `${number.format(amount)} ${units[index]}`; }
