"use client";

import type { components } from "@studio/api-client";
import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Clapperboard, ImageIcon, PackageSearch, Palette, Pencil, Plus, Save, Upload, UsersRound } from "lucide-react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Suspense, useState } from "react";
import { usePermissions } from "@/components/auth-context";
import { useScopedEntityId, useStudioScope } from "@/components/studio-scope";
import { Badge, Button, Card, Field, PageHeader, SkeletonRows, StatePanel, inputClass, textareaClass } from "@/components/ui";
import { api } from "@/lib/api";
import { includeCurrentOption, languageOptions, timeZoneOptions } from "@/lib/form-options";
import { newIdempotencyKey } from "@/lib/problem";
import { apiError } from "@/lib/problem";
import { studioRoutes } from "@/lib/studio-routes";

export default function WorkspacePage(){
 return <Suspense fallback={<SkeletonRows/>}><WorkspaceContent/></Suspense>
}
function WorkspaceContent(){
 const {canOperate}=usePermissions();
 const {clientId}=useStudioScope();const id=useScopedEntityId("workspaceId");const brandOnly=usePathname().endsWith("/brands");const qc=useQueryClient();const[show,setShow]=useState(false);const[editing,setEditing]=useState(false);const[name,setName]=useState("");const[tone,setTone]=useState("");const[primaryLanguage,setPrimaryLanguage]=useState<"vi"|"en">("vi");
 const workspace=useQuery({queryKey:["workspace",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}",{params:{path:{clientId,workspaceId:id}}});if(error||!data)throw apiError(error,"Không thể tải workspace.");return data}});
 const results=useQueries({queries:[
  {queryKey:["brands",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/brands",{params:{path:{clientId,workspaceId:id}}});if(error||!data)throw apiError(error,"Không thể tải thương hiệu.");return data}},
  {queryKey:["products",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products",{params:{path:{clientId,workspaceId:id},query:{}}});if(error||!data)throw apiError(error,"Không thể tải sản phẩm.");return data}},
  {queryKey:["media",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets",{params:{path:{clientId,workspaceId:id},query:{}}});if(error||!data)throw apiError(error,"Không thể tải media.");return data}},
  {queryKey:["campaigns",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/campaigns",{params:{path:{clientId,workspaceId:id},query:{}}});if(error||!data)throw apiError(error,"Không thể tải campaign.");return data}},
  {queryKey:["characters",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/characters",{params:{path:{clientId,workspaceId:id}}});if(error||!data)throw apiError(error,"Không thể tải nhân vật.");return data}},
 ]});
 const create=useMutation({mutationFn:async()=>{const{data,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/brands",{params:{path:{clientId,workspaceId:id},header:{"Idempotency-Key":newIdempotencyKey()}},body:{name,primaryLanguage,toneOfVoice:tone,logoAssetIds:[],preferredTerminology:[],prohibitedTerminology:[],targetAudience:"",mainMessage:"",defaultCta:"",defaultDisclaimer:"",defaultVideoStyle:"",defaultMusicStyle:"",changeSummary:"Hồ sơ ban đầu"}});if(error||!data)throw apiError(error,"Không thể tạo thương hiệu.");return data},onSuccess:async()=>{setShow(false);setName("");setTone("");setPrimaryLanguage("vi");await qc.invalidateQueries({queryKey:["brands",clientId,id]})}});
 if(!clientId)return <StatePanel title="Thiếu phạm vi khách hàng">Mở workspace từ trang chi tiết khách hàng để giữ ranh giới dữ liệu chính xác.</StatePanel>;if(workspace.isLoading)return <SkeletonRows/>;if(workspace.error)return <StatePanel title="Không thể tải workspace" tone="danger">{workspace.error.message}</StatePanel>;
 const [brands,products,media,campaigns,characters]=results;return <><Link href={brandOnly?studioRoutes.workspace(clientId,id):studioRoutes.client(clientId)} className="mb-5 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--moss)]"><ArrowLeft className="size-4"/>{brandOnly?"Tổng quan workspace":"Khách hàng"}</Link><PageHeader eyebrow={brandOnly?workspace.data!.name:"Workspace"} title={brandOnly?"Thương hiệu":workspace.data!.name} description={brandOnly?"Quản lý màu sắc, thuật ngữ, CTA và giọng điệu dùng xuyên suốt nội dung.":`Múi giờ ${workspace.data!.timezone}. Mọi truy vấn dưới đây được khóa theo khách hàng và workspace.`} action={canOperate ? <div className="flex flex-wrap gap-2">{!brandOnly?<Button className="bg-transparent text-[var(--ink)] ring-1 ring-[var(--line)] hover:bg-white" onClick={()=>setEditing(v=>!v)}><Pencil className="mr-2 size-4"/>{editing?"Đóng chỉnh sửa":"Chỉnh sửa"}</Button>:null}<Button onClick={()=>setShow(v=>!v)}><Plus className="mr-2 size-4"/>Thêm thương hiệu</Button></div> : undefined}/>
 {canOperate&&editing&&!brandOnly?<WorkspaceEditor key={workspace.data!.version} data={workspace.data!} clientId={clientId} onClose={()=>setEditing(false)}/>:null}
 {canOperate && show?<Card className="mb-6 p-6"><div className="grid gap-4 md:grid-cols-2"><Field label="Tên thương hiệu"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Ngôn ngữ chính"><select className={inputClass} value={primaryLanguage} onChange={e=>setPrimaryLanguage(e.target.value as "vi"|"en")}>{languageOptions.map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select></Field><div className="md:col-span-2"><Field label="Giọng điệu"><textarea className={textareaClass} value={tone} onChange={e=>setTone(e.target.value)}/></Field></div></div>{create.error?<p className="mt-3 text-sm text-[var(--coral)]">{create.error.message}</p>:null}<div className="mt-4"><Button disabled={create.isPending||name.length<2} onClick={()=>create.mutate()}>{create.isPending?"Đang tạo…":"Tạo thương hiệu"}</Button></div></Card>:null}
 {!brandOnly&&canOperate?<Card className="mb-7 flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="mr-auto"><h2 className="font-serif text-xl font-bold">Bắt đầu nhanh</h2><p className="mt-1 text-sm text-[var(--muted)]">Chuẩn bị dữ liệu an toàn trước khi đi vào workflow xuất bản hoặc Ads.</p></div><div className="flex flex-wrap gap-2"><Link className="inline-flex min-h-11 items-center rounded-full bg-white px-4 text-sm font-semibold text-[var(--ink)] ring-1 ring-[var(--line)] hover:bg-[#edf0e7]" href={studioRoutes.products(clientId,id)}><Plus className="mr-2 size-4"/>Thêm sản phẩm</Link><Link className="inline-flex min-h-11 items-center rounded-full bg-white px-4 text-sm font-semibold text-[var(--ink)] ring-1 ring-[var(--line)] hover:bg-[#edf0e7]" href={studioRoutes.media(clientId,id)}><Upload className="mr-2 size-4"/>Upload media</Link><Link className="inline-flex min-h-11 items-center rounded-full bg-[var(--ink)] px-4 text-sm font-semibold text-white hover:bg-[var(--moss)]" href={studioRoutes.campaigns(clientId,id)}><Plus className="mr-2 size-4"/>Tạo chiến dịch</Link></div></Card>:null}
 {!brandOnly?<div className="mb-7 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Summary icon={Palette} label="Thương hiệu" count={brands.data?.items.length} href={studioRoutes.brands(clientId,id)}/><Summary icon={PackageSearch} label="Sản phẩm" count={products.data?.items.length} href={studioRoutes.products(clientId,id)}/><Summary icon={ImageIcon} label="Media" count={media.data?.items.length} href={studioRoutes.media(clientId,id)}/><Summary icon={Clapperboard} label="Chiến dịch" count={campaigns.data?.items.length} href={studioRoutes.campaigns(clientId,id)}/><Summary icon={UsersRound} label="Nhân vật" count={characters.data?.items.length} href={studioRoutes.characters(clientId,id)}/></div>:null}
 <section id="brands"><h2 className="mb-4 font-serif text-2xl font-bold">Hồ sơ thương hiệu</h2>{brands.isLoading?<SkeletonRows/>:brands.error?<StatePanel title="Không thể tải thương hiệu" tone="danger">{brands.error.message}</StatePanel>:brands.data?.items.length===0?<StatePanel title="Chưa có thương hiệu">Tạo hồ sơ để khóa màu sắc, thuật ngữ, CTA và giọng điệu trước khi tạo nội dung.</StatePanel>:<div className="grid gap-4 md:grid-cols-2">{brands.data?.items.map(item=><Link key={item.id} href={studioRoutes.brand(clientId,id,item.id)}><Card className="h-full p-5 transition hover:border-[var(--moss)]"><div className="flex items-center justify-between"><h3 className="font-serif text-xl font-bold">{item.name}</h3><Badge tone={item.status==="ACTIVE"?"good":"neutral"}>{item.status}</Badge></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{item.toneOfVoice||"Chưa mô tả giọng điệu"}</p><p className="mt-4 text-xs font-bold uppercase tracking-wider text-[var(--moss)]">Phiên bản {item.currentVersion}</p></Card></Link>)}</div>}</section></>;
}
function Summary({icon:Icon,label,count,href}:{icon:typeof Palette;label:string;count?:number;href:string}){return <Link href={href}><Card className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-2xl bg-[#edf0e7]"><Icon className="size-5 text-[var(--moss)]"/></span><span><span className="block text-2xl font-bold">{count??"—"}</span><span className="text-sm text-[var(--muted)]">{label}</span></span></Card></Link>}

type Workspace = components["schemas"]["Workspace"];
type WorkspaceInput = components["schemas"]["WorkspaceInput"];

function WorkspaceEditor({data,clientId,onClose}:{data:Workspace;clientId:string;onClose:()=>void}){const qc=useQueryClient();const[form,setForm]=useState<WorkspaceInput>({name:data.name,slug:data.slug,timezone:data.timezone,version:data.version});const save=useMutation({mutationFn:async()=>{const{data:updated,error}=await api.PUT("/clients/{clientId}/workspaces/{workspaceId}",{params:{path:{clientId,workspaceId:data.id}},body:{...form,version:data.version}});if(error||!updated)throw apiError(error,"Không thể cập nhật workspace.");return updated},onSuccess:async()=>{await Promise.all([qc.invalidateQueries({queryKey:["workspace",clientId,data.id]}),qc.invalidateQueries({queryKey:["workspaces",clientId]})]);onClose()}});return <Card className="mb-6 p-6"><h2 className="font-serif text-xl font-bold">Chỉnh sửa workspace</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><Field label="Tên workspace"><input className={inputClass} value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></Field><Field label="Slug"><input className={inputClass} value={form.slug} onChange={e=>setForm(v=>({...v,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"" )}))}/></Field><Field label="Múi giờ"><select className={inputClass} value={form.timezone??""} onChange={e=>setForm(v=>({...v,timezone:e.target.value}))}>{includeCurrentOption(timeZoneOptions,form.timezone).map((option)=><option key={option.value} value={option.value}>{option.label}</option>)}</select></Field></div>{save.error?<p role="alert" className="mt-4 text-sm font-semibold text-[var(--coral)]">{save.error.message}</p>:null}<div className="mt-5 flex gap-3"><Button disabled={save.isPending||form.name.trim().length<2||!form.slug} onClick={()=>save.mutate()}><Save className="mr-2 size-4"/>{save.isPending?"Đang lưu…":"Lưu thay đổi"}</Button><Button className="bg-transparent text-[var(--ink)] ring-1 ring-[var(--line)] hover:bg-white" onClick={onClose}>Hủy</Button></div></Card>}
