"use client";

import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Clapperboard, ImageIcon, PackageSearch, Palette, Plus, UsersRound } from "lucide-react";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { usePermissions } from "@/components/auth-context";
import { Badge, Button, Card, Field, PageHeader, SkeletonRows, StatePanel, inputClass, textareaClass } from "@/components/ui";
import { api } from "@/lib/api";
import { newIdempotencyKey } from "@/lib/problem";
import { apiError } from "@/lib/problem";

export default function WorkspacePage(){
 return <Suspense fallback={<SkeletonRows/>}><WorkspaceContent/></Suspense>
}
function WorkspaceContent(){
 const {canOperate}=usePermissions();
 const {id}=useParams<{id:string}>();const clientId=useSearchParams().get("clientId")??"";const qc=useQueryClient();const[show,setShow]=useState(false);const[name,setName]=useState("");const[tone,setTone]=useState("");
 const workspace=useQuery({queryKey:["workspace",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}",{params:{path:{clientId,workspaceId:id}}});if(error||!data)throw apiError(error,"Không thể tải workspace.");return data}});
 const results=useQueries({queries:[
  {queryKey:["brands",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/brands",{params:{path:{clientId,workspaceId:id}}});if(error||!data)throw apiError(error,"Không thể tải thương hiệu.");return data}},
  {queryKey:["products",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products",{params:{path:{clientId,workspaceId:id},query:{}}});if(error||!data)throw apiError(error,"Không thể tải sản phẩm.");return data}},
  {queryKey:["media",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets",{params:{path:{clientId,workspaceId:id},query:{}}});if(error||!data)throw apiError(error,"Không thể tải media.");return data}},
  {queryKey:["campaigns",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/campaigns",{params:{path:{clientId,workspaceId:id},query:{}}});if(error||!data)throw apiError(error,"Không thể tải campaign.");return data}},
  {queryKey:["characters",clientId,id],enabled:!!clientId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/characters",{params:{path:{clientId,workspaceId:id}}});if(error||!data)throw apiError(error,"Không thể tải nhân vật.");return data}},
 ]});
 const create=useMutation({mutationFn:async()=>{const{data,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/brands",{params:{path:{clientId,workspaceId:id},header:{"Idempotency-Key":newIdempotencyKey()}},body:{name,primaryLanguage:"vi",toneOfVoice:tone,logoAssetIds:[],preferredTerminology:[],prohibitedTerminology:[],targetAudience:"",mainMessage:"",defaultCta:"",defaultDisclaimer:"",defaultVideoStyle:"",defaultMusicStyle:"",changeSummary:"Hồ sơ ban đầu"}});if(error||!data)throw apiError(error,"Không thể tạo thương hiệu.");return data},onSuccess:async()=>{setShow(false);setName("");setTone("");await qc.invalidateQueries({queryKey:["brands",clientId,id]})}});
 if(!clientId)return <StatePanel title="Thiếu phạm vi khách hàng">Mở workspace từ trang chi tiết khách hàng để giữ ranh giới dữ liệu chính xác.</StatePanel>;if(workspace.isLoading)return <SkeletonRows/>;if(workspace.error)return <StatePanel title="Không thể tải workspace" tone="danger">{workspace.error.message}</StatePanel>;
 const [brands,products,media,campaigns,characters]=results;return <><Link href={`/clients/${clientId}`} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--moss)]"><ArrowLeft className="size-4"/>Khách hàng</Link><PageHeader eyebrow="Workspace" title={workspace.data!.name} description={`Múi giờ ${workspace.data!.timezone}. Mọi truy vấn dưới đây được khóa theo client và workspace.`} action={canOperate ? <Button onClick={()=>setShow(v=>!v)}><Plus className="mr-2 size-4"/>Thêm thương hiệu</Button> : undefined}/>
 {canOperate && show?<Card className="mb-6 p-6"><div className="grid gap-4 md:grid-cols-2"><Field label="Tên thương hiệu"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Ngôn ngữ chính"><input className={inputClass} value="Tiếng Việt" disabled/></Field><div className="md:col-span-2"><Field label="Giọng điệu"><textarea className={textareaClass} value={tone} onChange={e=>setTone(e.target.value)}/></Field></div></div>{create.error?<p className="mt-3 text-sm text-[var(--coral)]">{create.error.message}</p>:null}<div className="mt-4"><Button disabled={create.isPending||name.length<2} onClick={()=>create.mutate()}>{create.isPending?"Đang tạo…":"Tạo thương hiệu"}</Button></div></Card>:null}
 <div className="mb-7 grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Summary icon={Palette} label="Thương hiệu" count={brands.data?.items.length} href="#brands"/><Summary icon={PackageSearch} label="Sản phẩm" count={products.data?.items.length} href={`/products?clientId=${clientId}&workspaceId=${id}`}/><Summary icon={ImageIcon} label="Media" count={media.data?.items.length} href={`/media?clientId=${clientId}&workspaceId=${id}`}/><Summary icon={Clapperboard} label="Campaign" count={campaigns.data?.items.length} href={`/campaigns?clientId=${clientId}&workspaceId=${id}`}/><Summary icon={UsersRound} label="Nhân vật" count={characters.data?.items.length} href={`/settings/characters?clientId=${clientId}&workspaceId=${id}`}/></div>
 <section id="brands"><h2 className="mb-4 font-serif text-2xl font-bold">Hồ sơ thương hiệu</h2>{brands.isLoading?<SkeletonRows/>:brands.error?<StatePanel title="Không thể tải thương hiệu" tone="danger">{brands.error.message}</StatePanel>:brands.data?.items.length===0?<StatePanel title="Chưa có thương hiệu">Tạo hồ sơ để khóa màu sắc, thuật ngữ, CTA và giọng điệu trước khi tạo nội dung.</StatePanel>:<div className="grid gap-4 md:grid-cols-2">{brands.data?.items.map(item=><Link key={item.id} href={`/brands/${item.id}?clientId=${clientId}&workspaceId=${id}`}><Card className="h-full p-5 transition hover:border-[var(--moss)]"><div className="flex items-center justify-between"><h3 className="font-serif text-xl font-bold">{item.name}</h3><Badge tone={item.status==="ACTIVE"?"good":"neutral"}>{item.status}</Badge></div><p className="mt-3 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{item.toneOfVoice||"Chưa mô tả giọng điệu"}</p><p className="mt-4 text-xs font-bold uppercase tracking-wider text-[var(--moss)]">Phiên bản {item.currentVersion}</p></Card></Link>)}</div>}</section></>;
}
function Summary({icon:Icon,label,count,href}:{icon:typeof Palette;label:string;count?:number;href:string}){return <Link href={href}><Card className="flex items-center gap-4 p-5"><span className="grid size-11 place-items-center rounded-2xl bg-[#edf0e7]"><Icon className="size-5 text-[var(--moss)]"/></span><span><span className="block text-2xl font-bold">{count??"—"}</span><span className="text-sm text-[var(--muted)]">{label}</span></span></Card></Link>}
