"use client";

import type { components } from "@studio/api-client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowDown, ArrowUp, Ban, Check, Copy, Download, Film, RefreshCw, Save, Star, Trash2 } from "lucide-react";
import { Suspense, useState } from "react";
import { usePermissions } from "@/components/auth-context";
import { CampaignHeader, GenerationPanel, useCampaignRoute } from "@/components/campaign-workflow";
import { MediaAssetPicker } from "@/components/media-asset-picker";
import { Badge, Button, Card, Field, SkeletonRows, StatePanel, inputClass, textareaClass } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError, newIdempotencyKey } from "@/lib/problem";

type Scene = components["schemas"]["CampaignScene"];
type Direction = components["schemas"]["SceneDirection"];
type Generation = components["schemas"]["SceneGeneration"];
type Review = components["schemas"]["SceneGenerationReview"];
type Asset = components["schemas"]["MediaAsset"];
export default function ScenesPage() { return <Suspense fallback={<SkeletonRows />}><Scenes /></Suspense>; }

function Scenes() {
  const { canOperate } = usePermissions();
  const scope = useCampaignRoute();
  const qc = useQueryClient();
  const query = useQuery({ queryKey: ["campaign-scenes", scope.campaignId], enabled: !!scope.clientId && !!scope.workspaceId, queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes", { params: { path: scope } }); if (error || !data) throw apiError(error, "Không thể tải scenes."); return data; } });
  const campaign = useQuery({ queryKey: ["campaign", scope.clientId, scope.workspaceId, scope.campaignId], enabled: !!scope.clientId && !!scope.workspaceId, queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}", { params: { path: scope } }); if (error || !data) throw apiError(error, "Không thể tải sản phẩm của campaign."); return data; } });
  const productMedia = useQuery({ queryKey: ["media", scope.clientId, scope.workspaceId, "scene-product", campaign.data?.productId], enabled: !!campaign.data?.productId, queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets", { params: { path: { clientId: scope.clientId, workspaceId: scope.workspaceId }, query: { productId: campaign.data!.productId, status: "APPROVED" } } }); if (error || !data) throw apiError(error, "Không thể tải media đã duyệt của sản phẩm."); const now = Date.now(); return { ...data, items: data.items.filter((asset) => !asset.expiresAt || new Date(asset.expiresAt).getTime() > now) }; } });
  const eligibleMedia = productMedia.data?.items.filter((asset) => ["IMAGE", "VIDEO", "LOGO", "SCREENSHOT", "SCREEN_RECORDING"].includes(asset.assetType)) ?? [];
  const refresh = () => qc.invalidateQueries({ queryKey: ["campaign-scenes", scope.campaignId] });
  const reorder = useMutation({ mutationFn: async (ids: string[]) => { const { data, error } = await api.PUT("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/reorder", { params: { path: scope }, body: { sceneIds: ids } }); if (error || !data) throw apiError(error, "Không thể đổi thứ tự scene."); return data; }, onSuccess: refresh });
  const move = (index: number, offset: number) => { if (!query.data) return; const ids = query.data.items.map((item) => item.id); [ids[index], ids[index + offset]] = [ids[index + offset]!, ids[index]!]; reorder.mutate(ids); };
  return <CampaignHeader active="/scenes" title="Scene Director" description="Scene chỉ được tham chiếu media APPROVED của đúng sản phẩm campaign; picker dùng tên và danh mục thay cho UUID thô."><GenerationPanel operation="SCENES" />{productMedia.error ? <StatePanel title="Không thể tải Product Media" tone="danger">{productMedia.error.message}</StatePanel> : null}{reorder.error ? <StatePanel title="Không thể sắp xếp" tone="danger">{reorder.error.message}</StatePanel> : null}{query.isLoading ? <SkeletonRows /> : query.error ? <StatePanel title="Không thể tải scenes" tone="danger">{query.error.message}</StatePanel> : query.data?.items.length === 0 ? <StatePanel title="Chưa có scene">Duyệt script, chọn đúng hai nhân vật rồi chạy AI scenes.</StatePanel> : <div className="grid gap-5">{query.data?.items.map((item, index) => <SceneCard key={item.id} item={item} productMedia={eligibleMedia} scope={scope} onChanged={refresh} controls={canOperate ? <div className="flex gap-1"><button aria-label="Đưa lên" disabled={index === 0 || reorder.isPending} className="rounded-full p-2 hover:bg-[#edf0e7] disabled:opacity-30" onClick={() => move(index, -1)}><ArrowUp className="size-4" /></button><button aria-label="Đưa xuống" disabled={index === query.data.items.length - 1 || reorder.isPending} className="rounded-full p-2 hover:bg-[#edf0e7] disabled:opacity-30" onClick={() => move(index, 1)}><ArrowDown className="size-4" /></button></div> : null} />)}</div>}</CampaignHeader>;
}

function SceneCard({ item, productMedia, scope, onChanged, controls }: { item: Scene; productMedia: Asset[]; scope: ReturnType<typeof useCampaignRoute>; onChanged: () => Promise<unknown>; controls: React.ReactNode }) {
  const { canOperate, canReview } = usePermissions();
  const [direction, setDirection] = useState<Direction>(item.direction);
  const update = useMutation({ mutationFn: async () => { const { data, error } = await api.PUT("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}", { params: { path: { ...scope, sceneId: item.id } }, body: { direction, version: item.version } }); if (error || !data) throw apiError(error, "Scene không đạt thời lượng, Product Truth hoặc guardrail hai nhân vật."); return data; }, onSuccess: onChanged });
  const approve = useMutation({ mutationFn: async () => { const { data, error } = await api.POST("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/approve", { params: { path: { ...scope, sceneId: item.id } }, body: { version: item.version, notes: "Đã duyệt direction, references và guardrails" } }); if (error || !data) throw apiError(error, "Không thể duyệt scene."); return data; }, onSuccess: onChanged });
  const duplicate = useMutation({ mutationFn: async () => { const { data, error } = await api.POST("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/duplicate", { params: { path: { ...scope, sceneId: item.id } } }); if (error || !data) throw apiError(error, "Không thể nhân bản scene."); return data; }, onSuccess: onChanged });
  const remove = useMutation({ mutationFn: async () => { const { error } = await api.DELETE("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}", { params: { path: { ...scope, sceneId: item.id } }, body: { version: item.version } }); if (error) throw apiError(error, "Không thể xóa scene."); }, onSuccess: onChanged });
  const change = <K extends keyof Direction>(key: K, value: Direction[K]) => setDirection((current) => ({ ...current, [key]: value }));
  const locked = item.status === "APPROVED";
  const error = update.error ?? approve.error ?? duplicate.error ?? remove.error;
  return <Card className="p-6">
    <div className="mb-5 flex flex-wrap items-center gap-2"><span className="grid size-9 place-items-center rounded-full bg-[var(--ink)] font-bold text-white">{item.order}</span><h2 className="font-serif text-xl font-bold">{item.sceneKey}</h2><Badge tone={locked ? "good" : "warn"}>{item.status}</Badge><Badge>{direction.generationMethod}</Badge><span className="ml-auto text-xs text-[var(--muted)]">{direction.durationSeconds}s · ${direction.expectedCostUsd.toFixed(4)} · v{item.currentVersion}</span>{controls}</div>
    <div className="grid gap-4 md:grid-cols-2"><Field label="Dialogue"><textarea disabled={locked || !canOperate} className={textareaClass} value={direction.dialogue} onChange={(e) => change("dialogue", e.target.value)} /></Field><Field label="Seedance prompt"><textarea disabled={locked || !canOperate} className={textareaClass} value={direction.seedancePrompt} onChange={(e) => change("seedancePrompt", e.target.value)} /></Field><Field label="Hành động người nói"><input disabled={locked || !canOperate} className={inputClass} value={direction.speakerAction} onChange={(e) => change("speakerAction", e.target.value)} /></Field><Field label="Hành động người nghe"><input disabled={locked || !canOperate} className={inputClass} value={direction.listenerAction} onChange={(e) => change("listenerAction", e.target.value)} /></Field><Field label="Camera"><input disabled={locked || !canOperate} className={inputClass} value={direction.camera} onChange={(e) => change("camera", e.target.value)} /></Field><Field label="Môi trường"><input disabled={locked || !canOperate} className={inputClass} value={direction.environment} onChange={(e) => change("environment", e.target.value)} /></Field><Field label="Product placement"><input disabled={locked || !canOperate} className={inputClass} value={direction.productPlacement} onChange={(e) => change("productPlacement", e.target.value)} /></Field><Field label="Thời lượng (giây)"><input disabled={locked || !canOperate} className={inputClass} type="number" min={3} max={15} value={direction.durationSeconds} onChange={(e) => change("durationSeconds", Number(e.target.value))} /></Field><div className="md:col-span-2"><MediaAssetPicker assets={productMedia} value={direction.referenceAssetIds} onChange={(ids) => change("referenceAssetIds", ids)} label="Product Media tham chiếu" disabled={locked || !canOperate} /></div><Field label="Product fact IDs bắt buộc"><input disabled={locked || !canOperate} className={inputClass} value={direction.requiredProductFactIds.join(", ")} onChange={(e) => change("requiredProductFactIds", e.target.value.split(",").map((value) => value.trim()).filter(Boolean))} /></Field></div>
    {error ? <p className="mt-4 text-sm text-[var(--coral)]">{error.message}</p> : null}<div className="mt-5 flex flex-wrap gap-2">{canOperate && !locked ? <><Button className="bg-white text-[var(--ink)] ring-1 ring-[var(--line)]" disabled={update.isPending} onClick={() => update.mutate()}><Save className="mr-2 size-4" />Lưu version</Button><Button className="bg-white text-[var(--ink)] ring-1 ring-[var(--line)]" disabled={duplicate.isPending} onClick={() => duplicate.mutate()}><Copy className="mr-2 size-4" />Nhân bản</Button><Button className="bg-[var(--coral)]" disabled={remove.isPending} onClick={() => remove.mutate()}><Trash2 className="mr-2 size-4" />Xóa</Button></> : null}{canReview && !locked ? <Button disabled={approve.isPending} onClick={() => approve.mutate()}><Check className="mr-2 size-4" />Duyệt</Button> : null}</div>{locked && direction.generationMethod === "seedance" ? <SceneGenerationPanel sceneId={item.id} productMedia={productMedia} scope={scope} onSelected={onChanged} /> : null}
  </Card>;
}

const terminalGenerationStates = new Set(["APPROVED", "REJECTED", "FAILED", "CANCELLED"]);

function SceneGenerationPanel({ sceneId, productMedia, scope, onSelected }: { sceneId: string; productMedia: Asset[]; scope: ReturnType<typeof useCampaignRoute>; onSelected: () => Promise<unknown> }) {
  const { canOperate } = usePermissions();
  const qc = useQueryClient();
  const path = { ...scope, sceneId };
  const queryKey = ["scene-generations", scope.campaignId, sceneId];
  const generations = useQuery({
    queryKey,
    refetchInterval: (query) => query.state.data?.items.some((item) => !terminalGenerationStates.has(item.status) && item.status !== "REVIEW_REQUIRED") ? 2500 : false,
    queryFn: async () => { const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/generations", { params: { path } }); if (error || !data) throw apiError(error, "Không thể tải Seedance takes."); return data; },
  });
  const refresh = async () => { await qc.invalidateQueries({ queryKey }); };
  const start = useMutation({ mutationFn: async () => { const { data, error } = await api.POST("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/generations", { params: { path, header: { "Idempotency-Key": newIdempotencyKey() } }, body: { resolution: "720p", aspectRatio: "9:16", generateAudio: true } }); if (error || !data) throw apiError(error, "Không thể tạo video; scene phải được duyệt và job tính phí không tự retry."); return data; }, onSuccess: refresh });
  return <section className="mt-6 border-t border-[var(--line)] pt-6"><div className="flex flex-wrap items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#edf0e7]"><Film className="size-5" /></span><div className="flex-1"><h3 className="font-serif text-lg font-bold">Seedance takes</h3><p className="text-xs text-[var(--muted)]">Provider output được tải ngay về R2, transcribe, QC rồi mới cho review.</p></div>{canOperate ? <Button disabled={start.isPending || generations.data?.items.some((item) => !terminalGenerationStates.has(item.status) && item.status !== "REVIEW_REQUIRED")} onClick={() => start.mutate()}>{start.isPending ? <RefreshCw className="mr-2 size-4 animate-spin" /> : null}Tạo take · 720p</Button> : null}</div>{start.error || generations.error ? <p className="mt-3 text-sm text-[var(--coral)]">{(start.error ?? generations.error)?.message}</p> : null}<div className="mt-4 grid gap-3">{generations.data?.items.map((item) => <GenerationTake key={item.id} item={item} productMedia={productMedia} path={path} onChanged={refresh} onSelected={onSelected} />)}</div></section>;
}

function GenerationTake({ item, productMedia, path, onChanged, onSelected }: { item: Generation; productMedia: Asset[]; path: ReturnType<typeof useCampaignRoute> & { sceneId: string }; onChanged: () => Promise<unknown>; onSelected: () => Promise<unknown> }) {
  const { canOperate, canReview } = usePermissions();
  const generationPath = { ...path, generationId: item.id };
  const [notes, setNotes] = useState("Đã kiểm tra hai nhân vật, sản phẩm, crop, logo và safe zone CTA.");
  const [review, setReview] = useState<Omit<Review, "action" | "version" | "notes">>({ characterCount: 2, duplicateCharacter: false, duplicateProduct: false, productColorMismatch: false, blurOrLowQualityWarning: false, cropWarning: false, subtitleOverflow: false, logoOverlap: false, ctaSafeZoneViolation: false });
  const [edit, setEdit] = useState(item.edit ?? { trimStartMs: 0, trimEndMs: null, muteAudio: false, transition: "CUT" as const, replacementAssetId: null, attachedProductAssetIds: [], subtitlePreview: true, version: 1 });
  const cancel = useMutation({ mutationFn: async () => { const { data, error } = await api.POST("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/generations/{generationId}/cancel", { params: { path: generationPath } }); if (error || !data) throw apiError(error, "Chỉ task local/provider queued mới có thể hủy."); return data; }, onSuccess: onChanged });
  const decide = useMutation({ mutationFn: async (action: "APPROVE" | "REJECT") => { const { data, error } = await api.PUT("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/generations/{generationId}/review", { params: { path: generationPath }, body: { ...review, action, version: item.version, notes } }); if (error || !data) throw apiError(error, "Checklist chưa đầy đủ hoặc QC chưa sẵn sàng."); return data; }, onSuccess: onChanged });
  const select = useMutation({ mutationFn: async () => { const { data, error } = await api.POST("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/generations/{generationId}/select", { params: { path: generationPath } }); if (error || !data) throw apiError(error, "Chỉ take đã duyệt mới được chọn."); return data; }, onSuccess: async () => { await onChanged(); await onSelected(); } });
  const saveEdit = useMutation({ mutationFn: async () => { const { data, error } = await api.PUT("/clients/{clientId}/workspaces/{workspaceId}/campaigns/{campaignId}/scenes/{sceneId}/generations/{generationId}/edit", { params: { path: generationPath }, body: edit }); if (error || !data) throw apiError(error, "Không thể lưu trim, audio, transition hoặc asset thay thế."); return data; }, onSuccess: async (data) => { if (data.edit) setEdit(data.edit); await onChanged(); } });
  const download = async () => { if (!item.outputAssetId) return; const { data, error } = await api.GET("/clients/{clientId}/workspaces/{workspaceId}/media-assets/{assetId}/download", { params: { path: { clientId: path.clientId, workspaceId: path.workspaceId, assetId: item.outputAssetId } } }); if (error || !data) throw apiError(error, "Không thể mở take."); window.open(data.url, "_blank", "noopener,noreferrer"); };
  const mutationError = cancel.error ?? decide.error ?? select.error ?? saveEdit.error;
  const editable = canOperate && (item.status === "REVIEW_REQUIRED" || item.status === "APPROVED");
  return <div className="rounded-2xl border border-[var(--line)] bg-white p-4">
    <div className="flex flex-wrap items-center gap-2"><Badge tone={item.status === "APPROVED" ? "good" : item.status === "FAILED" || item.status === "REJECTED" ? "danger" : item.status === "REVIEW_REQUIRED" ? "warn" : "neutral"}>{item.status}</Badge>{item.selected ? <Badge tone="good">Đã chọn</Badge> : null}<span className="text-xs text-[var(--muted)]">take #{item.attemptNumber} · {item.resolution} · {item.durationSeconds}s · ${item.actualCostUsd?.toFixed(4) ?? item.estimatedCostUsd.toFixed(4)}</span><span className="ml-auto text-xs text-[var(--muted)]">v{item.version}</span></div>
    {item.errorMessage ? <p className="mt-2 text-sm text-[var(--coral)]">{item.errorMessage}</p> : null}{item.transcription ? <div className="mt-3 rounded-xl bg-[#f4f5ef] p-3 text-xs"><strong>Transcript:</strong> {item.transcription.transcript || item.transcription.status}</div> : null}{item.qualityCheck ? <div className="mt-3 flex flex-wrap gap-2"><Badge tone={item.qualityCheck.deterministicPass ? "good" : "danger"}>Deterministic QC {item.qualityCheck.deterministicPass ? "pass" : "check"}</Badge><Badge tone={item.qualityCheck.transcriptPass ? "good" : "danger"}>Transcript</Badge><Badge tone={item.qualityCheck.videoDecodes ? "good" : "danger"}>Decode</Badge><Badge tone={item.qualityCheck.resolutionPass ? "good" : "danger"}>Resolution</Badge></div> : null}
    {editable ? <div className="mt-4 grid gap-3 rounded-2xl bg-[#f7f8f3] p-4 md:grid-cols-2"><Field label="Trim đầu (ms)"><input className={inputClass} type="number" min={0} value={edit.trimStartMs} onChange={(event) => setEdit((current) => ({ ...current, trimStartMs: Number(event.target.value) }))} /></Field><Field label="Trim cuối (ms, trống = hết)"><input className={inputClass} type="number" min={1} value={edit.trimEndMs ?? ""} onChange={(event) => setEdit((current) => ({ ...current, trimEndMs: event.target.value ? Number(event.target.value) : null }))} /></Field><Field label="Transition"><select className={inputClass} value={edit.transition} onChange={(event) => setEdit((current) => ({ ...current, transition: event.target.value as typeof current.transition }))}><option value="CUT">Cut</option><option value="CROSSFADE">Crossfade</option><option value="FADE_TO_BLACK">Fade to black</option></select></Field><div className="md:col-span-2"><MediaAssetPicker assets={productMedia.filter((asset) => asset.assetType === "VIDEO" || asset.assetType === "SCREEN_RECORDING")} value={edit.replacementAssetId ? [edit.replacementAssetId] : []} onChange={(ids) => setEdit((current) => ({ ...current, replacementAssetId: ids[0] ?? null }))} label="Video thay thế" multiple={false} /></div><div className="md:col-span-2"><MediaAssetPicker assets={productMedia} value={edit.attachedProductAssetIds} onChange={(ids) => setEdit((current) => ({ ...current, attachedProductAssetIds: ids }))} label="Product Media đính kèm" /></div><div className="flex flex-col justify-end gap-2 pb-2"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={edit.muteAudio} onChange={(event) => setEdit((current) => ({ ...current, muteAudio: event.target.checked }))} />Tắt audio</label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={edit.subtitlePreview} onChange={(event) => setEdit((current) => ({ ...current, subtitlePreview: event.target.checked }))} />Xem trước subtitle</label></div><Button className="md:col-span-2" disabled={saveEdit.isPending} onClick={() => saveEdit.mutate()}><Save className="mr-2 size-4" />Lưu edit metadata</Button></div> : null}
    {canReview && item.status === "REVIEW_REQUIRED" ? <div className="mt-4 grid gap-3"><Field label="Số nhân vật nhìn thấy"><input className={inputClass} type="number" min={0} value={review.characterCount} onChange={(event) => setReview((current) => ({ ...current, characterCount: Number(event.target.value) }))} /></Field><div className="grid gap-2 md:grid-cols-2">{(["duplicateCharacter", "duplicateProduct", "productColorMismatch", "blurOrLowQualityWarning", "cropWarning", "subtitleOverflow", "logoOverlap", "ctaSafeZoneViolation"] as const).map((key) => <label key={key} className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={review[key]} onChange={(event) => setReview((current) => ({ ...current, [key]: event.target.checked }))} />{key}</label>)}</div><Field label="Ghi chú review"><textarea className={textareaClass} value={notes} onChange={(event) => setNotes(event.target.value)} /></Field></div> : null}
    {mutationError ? <p className="mt-3 text-sm text-[var(--coral)]">{mutationError.message}</p> : null}<div className="mt-4 flex flex-wrap gap-2">{item.outputAssetId ? <Button className="bg-white text-[var(--ink)] ring-1 ring-[var(--line)]" onClick={() => void download()}><Download className="mr-2 size-4" />Mở video</Button> : null}{canOperate && (item.status === "QUEUED" || item.status === "PROVIDER_QUEUED") ? <Button className="bg-[var(--coral)]" disabled={cancel.isPending} onClick={() => cancel.mutate()}><Ban className="mr-2 size-4" />Hủy</Button> : null}{canReview && item.status === "REVIEW_REQUIRED" ? <><Button disabled={decide.isPending} onClick={() => decide.mutate("APPROVE")}><Check className="mr-2 size-4" />Duyệt take</Button><Button className="bg-[var(--coral)]" disabled={decide.isPending || !notes.trim()} onClick={() => decide.mutate("REJECT")}><Ban className="mr-2 size-4" />Từ chối</Button></> : null}{canReview && item.status === "APPROVED" && !item.selected ? <Button disabled={select.isPending} onClick={() => select.mutate()}><Star className="mr-2 size-4" />Chọn take</Button> : null}</div>
  </div>;
}
