"use client";

import { useMutation, useQueries, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Check, LockKeyhole, Plus, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { Badge, Button, Card, Field, PageHeader, SkeletonRows, StatePanel, inputClass, textareaClass } from "@/components/ui";
import { api } from "@/lib/api";
import { apiError } from "@/lib/problem";

export default function ProductPage(){return <Suspense fallback={<SkeletonRows/>}><ProductContent/></Suspense>}
function ProductContent(){const{id}=useParams<{id:string}>();const q=useSearchParams();const clientId=q.get("clientId")??"";const workspaceId=q.get("workspaceId")??"";const qc=useQueryClient();const[mode,setMode]=useState<"fact"|"claim"|null>(null);const[fact,setFact]=useState({factKey:"",label:"",exactValue:"",sourceName:"",sourceExcerpt:""});const[claim,setClaim]=useState({claimKind:"APPROVED",claimText:"",rationale:""});const path={clientId,workspaceId,productId:id};
 const product=useQuery({queryKey:["product",...Object.values(path)],enabled:!!clientId&&!!workspaceId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}",{params:{path}});if(error||!data)throw apiError(error,"Không thể tải sản phẩm.");return data}});
 const [facts,claims]=useQueries({queries:[{queryKey:["facts",id],enabled:!!clientId&&!!workspaceId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/facts",{params:{path}});if(error||!data)throw apiError(error,"Không thể tải fact.");return data}},{queryKey:["claims",id],enabled:!!clientId&&!!workspaceId,queryFn:async()=>{const{data,error}=await api.GET("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/claims",{params:{path}});if(error||!data)throw apiError(error,"Không thể tải claim.");return data}}]});
 const createFact=useMutation({mutationFn:async()=>{const{data,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/facts",{params:{path},body:{...fact,changeSummary:"Fact ban đầu"}});if(error||!data)throw apiError(error,"Không thể tạo fact.");return data},onSuccess:async()=>{setMode(null);setFact({factKey:"",label:"",exactValue:"",sourceName:"",sourceExcerpt:""});await qc.invalidateQueries({queryKey:["facts",id]})}});
 const approveFact=useMutation({mutationFn:async(item:{id:string;version:number})=>{const{data,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/facts/{factId}/approve",{params:{path:{...path,factId:item.id}},body:{lock:true,version:item.version}});if(error||!data)throw apiError(error,"Không thể duyệt fact.");return data},onSuccess:async()=>qc.invalidateQueries({queryKey:["facts",id]})});
 const createClaim=useMutation({mutationFn:async()=>{const{data,error}=await api.POST("/clients/{clientId}/workspaces/{workspaceId}/products/{productId}/claims",{params:{path},body:{...claim,claimKind:claim.claimKind as "APPROVED"|"PROHIBITED",factIds:[],mediaAssetIds:[],changeSummary:"Claim ban đầu"}});if(error||!data)throw apiError(error,"Không thể tạo claim.");return data},onSuccess:async()=>{setMode(null);setClaim({claimKind:"APPROVED",claimText:"",rationale:""});await qc.invalidateQueries({queryKey:["claims",id]})}});
 if(!clientId||!workspaceId)return <StatePanel title="Thiếu phạm vi workspace">Mở sản phẩm từ danh sách theo workspace.</StatePanel>;if(product.isLoading)return <SkeletonRows/>;if(product.error)return <StatePanel title="Không thể tải sản phẩm" tone="danger">{product.error.message}</StatePanel>;
 return <><Link href={`/products?clientId=${clientId}&workspaceId=${workspaceId}`} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--moss)]"><ArrowLeft className="size-4"/>Sản phẩm</Link><PageHeader eyebrow={`SKU ${product.data!.sku}`} title={product.data!.name} description="Product Truth là nguồn duy nhất cho các pipeline AI. Giá trị có biểu tượng khóa phải xuất hiện nguyên văn." action={<Badge tone={product.data!.status==="APPROVED"?"good":"warn"}>{product.data!.status}</Badge>}/>
 <Card className="mb-7 p-6"><h2 className="font-serif text-xl font-bold">Dữ liệu travel-luggage đã xác thực</h2><pre className="mt-4 overflow-auto rounded-2xl bg-[var(--ink)] p-4 text-xs leading-6 text-[#dfeac7]">{JSON.stringify(product.data!.verticalData,null,2)}</pre></Card>
 <div className="mb-4 flex items-center justify-between"><h2 className="font-serif text-2xl font-bold">Facts được xác minh</h2><Button onClick={()=>setMode(mode==="fact"?null:"fact")}><Plus className="mr-2 size-4"/>Thêm fact</Button></div>{mode==="fact"?<Card className="mb-5 p-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Fact key"><input className={inputClass} placeholder="external_dimensions" value={fact.factKey} onChange={e=>setFact(v=>({...v,factKey:e.target.value}))}/></Field><Field label="Nhãn"><input className={inputClass} value={fact.label} onChange={e=>setFact(v=>({...v,label:e.target.value}))}/></Field><Field label="Giá trị chính xác"><input className={inputClass} placeholder="55 x 36 x 23 cm" value={fact.exactValue} onChange={e=>setFact(v=>({...v,exactValue:e.target.value}))}/></Field><Field label="Nguồn"><input className={inputClass} value={fact.sourceName} onChange={e=>setFact(v=>({...v,sourceName:e.target.value}))}/></Field><div className="md:col-span-2"><Field label="Trích đoạn nguồn"><textarea className={textareaClass} value={fact.sourceExcerpt} onChange={e=>setFact(v=>({...v,sourceExcerpt:e.target.value}))}/></Field></div></div>{createFact.error?<p className="mt-3 text-sm text-[var(--coral)]">{createFact.error.message}</p>:null}<Button className="mt-4" disabled={createFact.isPending} onClick={()=>createFact.mutate()}>Lưu fact nháp</Button></Card>:null}
 {facts.isLoading?<SkeletonRows/>:facts.data?.items.length===0?<StatePanel title="Chưa có fact">Thêm giá, kích thước, cân nặng, bảo hành và các giá trị được trích từ nguồn.</StatePanel>:<div className="mb-8 grid gap-3">{facts.data?.items.map(item=><Card key={item.id} className="flex flex-col gap-3 p-5 md:flex-row md:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-bold">{item.label}</span><Badge tone={item.status==="APPROVED"?"good":"warn"}>{item.status}</Badge>{item.lockedValue?<LockKeyhole className="size-4 text-[var(--moss)]"/>:null}</div><p className="mt-2 font-mono text-sm">{item.exactValue}</p><p className="mt-1 text-xs text-[var(--muted)]">Nguồn: {item.sourceName}</p></div>{item.status!=="APPROVED"?<Button disabled={approveFact.isPending} onClick={()=>approveFact.mutate({id:item.id,version:item.version!})}><Check className="mr-2 size-4"/>Duyệt & khóa</Button>:null}</Card>)}</div>}
 <div className="mb-4 flex items-center justify-between"><h2 className="font-serif text-2xl font-bold">Claims</h2><Button onClick={()=>setMode(mode==="claim"?null:"claim")}><Plus className="mr-2 size-4"/>Thêm claim</Button></div>{mode==="claim"?<Card className="mb-5 p-5"><div className="grid gap-4"><Field label="Loại"><select className={inputClass} value={claim.claimKind} onChange={e=>setClaim(v=>({...v,claimKind:e.target.value}))}><option value="APPROVED">Được phép</option><option value="PROHIBITED">Bị cấm</option></select></Field><Field label="Nội dung claim"><textarea className={textareaClass} value={claim.claimText} onChange={e=>setClaim(v=>({...v,claimText:e.target.value}))}/></Field><Field label="Lý do"><textarea className={textareaClass} value={claim.rationale} onChange={e=>setClaim(v=>({...v,rationale:e.target.value}))}/></Field></div>{createClaim.error?<p className="mt-3 text-sm text-[var(--coral)]">{createClaim.error.message}</p>:null}<Button className="mt-4" onClick={()=>createClaim.mutate()}>Lưu claim nháp</Button></Card>:null}
 {claims.data?.items.length===0?<StatePanel title="Chưa có claim">Claim phổ quát về hành lý xách tay sẽ bị chặn nếu không có nguồn phê duyệt chính xác.</StatePanel>:<div className="grid gap-3">{claims.data?.items.map(item=><Card key={item.id} className="p-5"><div className="flex items-center gap-2"><ShieldAlert className="size-4"/><Badge tone={item.claimKind==="PROHIBITED"?"danger":"good"}>{item.claimKind}</Badge><Badge tone={item.status==="APPROVED"?"good":"warn"}>{item.status}</Badge></div><p className="mt-3 text-sm leading-6">{item.claimText}</p></Card>)}</div>}</>}
